### ISSUE TITLE
Unknown type name: NDArray-or-Symbol

### ISSUE THREAD

**Issue by pierric** [sighingnow/mxnet-haskell#1]
It seems that MXNet has changed many operators that the input could be 'NDArray', 'Symbol', or 'NDArray-or-Symbol'. So the current `makeNDArrayFunc` does not work as expected. What about replacing the argument type with a `class OpInput`, and making both `MXNet.Core.Base.NDArray.NDArray` and `MXNet.Core.Base.Symbol.Symbol` be an instance of this class?

```
    /mnt/c/Users/jiase/Develop/mxnet-haskell/mxnet/src/MXNet/Core/Base/Internal/TH/NDArray.hs:59:3: error:
        Illegal type constructor or class name: ‘unknown type name: NDArray-or-Symbol’
        When splicing a TH declaration:
          activation :: forall r . NDArrayOpResult r =>
                             unknown type name: NDArray-or-Symbol -> String -> IO r
```

**Comment by sighingnow** [comment]
Now the develop branch should be compatible with mxnet-1.2.0-rc.
